(ns signal-integrity.s-param
  "S-parameter representation and Touchstone export for 2-port networks.
  Restored from kami-si's `s_param` module (deleted PR #82). Each
  S-parameter entry is a `[magnitude phase-degrees]` pair.")

(defn s-parameter [freq-ghz s11 s21 s12 s22]
  {:freq-ghz freq-ghz :s11 s11 :s21 s21 :s12 s12 :s22 s22})

(defn s-param-metrics [insertion-loss-db return-loss-db bandwidth-3db-ghz]
  {:insertion-loss-db insertion-loss-db :return-loss-db return-loss-db :bandwidth-3db-ghz bandwidth-3db-ghz})

(defn- db20 [mag] (* 20.0 (/ (Math/log mag) (Math/log 10.0))))

(defn metrics
  "Summary metrics from S-parameter data: worst-case insertion loss (S21
  dB), worst-case return loss (S11 dB), and 3dB bandwidth (first
  frequency where |S21| drops 3dB from DC)."
  [sparam]
  (let [insertion-loss-db (reduce min ##Inf (map (fn [[mag _]] (db20 mag)) (:s21 sparam)))
        return-loss-db (reduce min ##Inf (map (fn [[mag _]] (- (db20 mag))) (:s11 sparam)))
        s21-db-0 (if-let [[mag _] (first (:s21 sparam))] (db20 mag) 0.0)
        bandwidth-3db-ghz (or (some (fn [[f [mag _]]] (when (< (db20 mag) (- s21-db-0 3.0)) f))
                                     (map vector (:freq-ghz sparam) (:s21 sparam)))
                               (last (:freq-ghz sparam))
                               0.0)]
    (s-param-metrics insertion-loss-db return-loss-db bandwidth-3db-ghz)))

(defn- fmt-e6 [x]
  #?(:clj (format "%.6e" (double x))
     :cljs (.toExponential (double x) 6)))
(defn- fmt-3 [x]
  #?(:clj (format "%.3f" (double x))
     :cljs (.toFixed (double x) 3)))

(defn export-touchstone
  "Export S-parameter data in Touchstone .s2p format (Version 1): `# GHz S
  MA R 50` header followed by frequency-ordered rows of `freq S11_mag
  S11_phase S21_mag S21_phase S12_mag S12_phase S22_mag S22_phase`."
  [sparam]
  (str "! Touchstone .s2p generated by kami-si\n"
       "# GHz S MA R 50\n"
       (apply str
              (map (fn [freq [s11m s11p] [s21m s21p] [s12m s12p] [s22m s22p]]
                     (str (fmt-e6 freq) "  "
                          (fmt-e6 s11m) " " (fmt-3 s11p) "  "
                          (fmt-e6 s21m) " " (fmt-3 s21p) "  "
                          (fmt-e6 s12m) " " (fmt-3 s12p) "  "
                          (fmt-e6 s22m) " " (fmt-3 s22p) "\n"))
                   (:freq-ghz sparam) (:s11 sparam) (:s21 sparam) (:s12 sparam) (:s22 sparam)))))
